development: &global_settings
  uri: <%= ENV['MONGO_URI'] %>
  # host: 127.0.0.1
  # database: transcribe-dev
  # port: 27017

test:
  database: transcribe-test
  <<: *global_settings

production:
  uri: <%= ENV['MONGO_URI'] %>

