development: &global_settings
  host: 127.0.0.1
  database: transcribe-dev
  port: 27017

test:
  database: scribe-test
  <<: *global_settings

production:
	uri: <%= ENV['MONGO_URI'] %>

  <<: *global_settings
